// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: core/protocol/src/main/proto/yeetcd/protocol/pipeline/pipeline.proto

package pipeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parameter_TYPE_CHECK int32

const (
	Parameter_STRING  Parameter_TYPE_CHECK = 0
	Parameter_NUMBER  Parameter_TYPE_CHECK = 1
	Parameter_BOOLEAN Parameter_TYPE_CHECK = 2
)

// Enum value maps for Parameter_TYPE_CHECK.
var (
	Parameter_TYPE_CHECK_name = map[int32]string{
		0: "STRING",
		1: "NUMBER",
		2: "BOOLEAN",
	}
	Parameter_TYPE_CHECK_value = map[string]int32{
		"STRING":  0,
		"NUMBER":  1,
		"BOOLEAN": 2,
	}
)

func (x Parameter_TYPE_CHECK) Enum() *Parameter_TYPE_CHECK {
	p := new(Parameter_TYPE_CHECK)
	*p = x
	return p
}

func (x Parameter_TYPE_CHECK) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Parameter_TYPE_CHECK) Descriptor() protoreflect.EnumDescriptor {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes[0].Descriptor()
}

func (Parameter_TYPE_CHECK) Type() protoreflect.EnumType {
	return &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes[0]
}

func (x Parameter_TYPE_CHECK) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Parameter_TYPE_CHECK.Descriptor instead.
func (Parameter_TYPE_CHECK) EnumDescriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{7, 0}
}

type WorkContextCondition_Operand int32

const (
	WorkContextCondition_EQUALS WorkContextCondition_Operand = 0
)

// Enum value maps for WorkContextCondition_Operand.
var (
	WorkContextCondition_Operand_name = map[int32]string{
		0: "EQUALS",
	}
	WorkContextCondition_Operand_value = map[string]int32{
		"EQUALS": 0,
	}
)

func (x WorkContextCondition_Operand) Enum() *WorkContextCondition_Operand {
	p := new(WorkContextCondition_Operand)
	*p = x
	return p
}

func (x WorkContextCondition_Operand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkContextCondition_Operand) Descriptor() protoreflect.EnumDescriptor {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes[1].Descriptor()
}

func (WorkContextCondition_Operand) Type() protoreflect.EnumType {
	return &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes[1]
}

func (x WorkContextCondition_Operand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkContextCondition_Operand.Descriptor instead.
func (WorkContextCondition_Operand) EnumDescriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{11, 0}
}

type PreviousWorkStatusCondition_Status int32

const (
	PreviousWorkStatusCondition_SUCCESS PreviousWorkStatusCondition_Status = 0
	PreviousWorkStatusCondition_FAILURE PreviousWorkStatusCondition_Status = 1
	PreviousWorkStatusCondition_ANY     PreviousWorkStatusCondition_Status = 2
)

// Enum value maps for PreviousWorkStatusCondition_Status.
var (
	PreviousWorkStatusCondition_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
		2: "ANY",
	}
	PreviousWorkStatusCondition_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
		"ANY":     2,
	}
)

func (x PreviousWorkStatusCondition_Status) Enum() *PreviousWorkStatusCondition_Status {
	p := new(PreviousWorkStatusCondition_Status)
	*p = x
	return p
}

func (x PreviousWorkStatusCondition_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreviousWorkStatusCondition_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes[2].Descriptor()
}

func (PreviousWorkStatusCondition_Status) Type() protoreflect.EnumType {
	return &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes[2]
}

func (x PreviousWorkStatusCondition_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreviousWorkStatusCondition_Status.Descriptor instead.
func (PreviousWorkStatusCondition_Status) EnumDescriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{12, 0}
}

type CustomWorkDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomWorkDefinition) Reset() {
	*x = CustomWorkDefinition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomWorkDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomWorkDefinition) ProtoMessage() {}

func (x *CustomWorkDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomWorkDefinition.ProtoReflect.Descriptor instead.
func (*CustomWorkDefinition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *CustomWorkDefinition) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type DynamicWorkGeneratingWorkDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicWorkGeneratingWorkDefinition) Reset() {
	*x = DynamicWorkGeneratingWorkDefinition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicWorkGeneratingWorkDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicWorkGeneratingWorkDefinition) ProtoMessage() {}

func (x *DynamicWorkGeneratingWorkDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicWorkGeneratingWorkDefinition.ProtoReflect.Descriptor instead.
func (*DynamicWorkGeneratingWorkDefinition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *DynamicWorkGeneratingWorkDefinition) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ContainerisedWorkDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Cmd           []string               `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerisedWorkDefinition) Reset() {
	*x = ContainerisedWorkDefinition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerisedWorkDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerisedWorkDefinition) ProtoMessage() {}

func (x *ContainerisedWorkDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerisedWorkDefinition.ProtoReflect.Descriptor instead.
func (*ContainerisedWorkDefinition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerisedWorkDefinition) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerisedWorkDefinition) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type CompoundWorkDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalWork     []*Work                `protobuf:"bytes,3,rep,name=finalWork,proto3" json:"finalWork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompoundWorkDefinition) Reset() {
	*x = CompoundWorkDefinition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompoundWorkDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompoundWorkDefinition) ProtoMessage() {}

func (x *CompoundWorkDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompoundWorkDefinition.ProtoReflect.Descriptor instead.
func (*CompoundWorkDefinition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *CompoundWorkDefinition) GetFinalWork() []*Work {
	if x != nil {
		return x.FinalWork
	}
	return nil
}

type WorkOutputPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkOutputPath) Reset() {
	*x = WorkOutputPath{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkOutputPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkOutputPath) ProtoMessage() {}

func (x *WorkOutputPath) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkOutputPath.ProtoReflect.Descriptor instead.
func (*WorkOutputPath) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *WorkOutputPath) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkOutputPath) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PreviousWork struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Work             *Work                  `protobuf:"bytes,1,opt,name=work,proto3" json:"work,omitempty"`
	OutputPathsMount string                 `protobuf:"bytes,2,opt,name=outputPathsMount,proto3" json:"outputPathsMount,omitempty"`
	StdOutEnvVar     string                 `protobuf:"bytes,3,opt,name=stdOutEnvVar,proto3" json:"stdOutEnvVar,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreviousWork) Reset() {
	*x = PreviousWork{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousWork) ProtoMessage() {}

func (x *PreviousWork) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousWork.ProtoReflect.Descriptor instead.
func (*PreviousWork) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *PreviousWork) GetWork() *Work {
	if x != nil {
		return x.Work
	}
	return nil
}

func (x *PreviousWork) GetOutputPathsMount() string {
	if x != nil {
		return x.OutputPathsMount
	}
	return ""
}

func (x *PreviousWork) GetStdOutEnvVar() string {
	if x != nil {
		return x.StdOutEnvVar
	}
	return ""
}

type Work struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to OneofTaskActions:
	//
	//	*Work_CustomWorkDefinition
	//	*Work_ContainerisedWorkDefinition
	//	*Work_CompoundWorkDefinition
	//	*Work_DynamicWorkGeneratingWorkDefinition
	OneofTaskActions isWork_OneofTaskActions `protobuf_oneof:"oneof_task_actions"`
	WorkContext      map[string]string       `protobuf:"bytes,7,rep,name=workContext,proto3" json:"workContext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OutputPaths      []*WorkOutputPath       `protobuf:"bytes,8,rep,name=outputPaths,proto3" json:"outputPaths,omitempty"`
	PreviousWork     []*PreviousWork         `protobuf:"bytes,9,rep,name=previousWork,proto3" json:"previousWork,omitempty"`
	Condition        *Condition              `protobuf:"bytes,10,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Work) Reset() {
	*x = Work{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Work) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Work) ProtoMessage() {}

func (x *Work) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Work.ProtoReflect.Descriptor instead.
func (*Work) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *Work) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Work) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Work) GetOneofTaskActions() isWork_OneofTaskActions {
	if x != nil {
		return x.OneofTaskActions
	}
	return nil
}

func (x *Work) GetCustomWorkDefinition() *CustomWorkDefinition {
	if x != nil {
		if x, ok := x.OneofTaskActions.(*Work_CustomWorkDefinition); ok {
			return x.CustomWorkDefinition
		}
	}
	return nil
}

func (x *Work) GetContainerisedWorkDefinition() *ContainerisedWorkDefinition {
	if x != nil {
		if x, ok := x.OneofTaskActions.(*Work_ContainerisedWorkDefinition); ok {
			return x.ContainerisedWorkDefinition
		}
	}
	return nil
}

func (x *Work) GetCompoundWorkDefinition() *CompoundWorkDefinition {
	if x != nil {
		if x, ok := x.OneofTaskActions.(*Work_CompoundWorkDefinition); ok {
			return x.CompoundWorkDefinition
		}
	}
	return nil
}

func (x *Work) GetDynamicWorkGeneratingWorkDefinition() *DynamicWorkGeneratingWorkDefinition {
	if x != nil {
		if x, ok := x.OneofTaskActions.(*Work_DynamicWorkGeneratingWorkDefinition); ok {
			return x.DynamicWorkGeneratingWorkDefinition
		}
	}
	return nil
}

func (x *Work) GetWorkContext() map[string]string {
	if x != nil {
		return x.WorkContext
	}
	return nil
}

func (x *Work) GetOutputPaths() []*WorkOutputPath {
	if x != nil {
		return x.OutputPaths
	}
	return nil
}

func (x *Work) GetPreviousWork() []*PreviousWork {
	if x != nil {
		return x.PreviousWork
	}
	return nil
}

func (x *Work) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type isWork_OneofTaskActions interface {
	isWork_OneofTaskActions()
}

type Work_CustomWorkDefinition struct {
	CustomWorkDefinition *CustomWorkDefinition `protobuf:"bytes,3,opt,name=customWorkDefinition,proto3,oneof"`
}

type Work_ContainerisedWorkDefinition struct {
	ContainerisedWorkDefinition *ContainerisedWorkDefinition `protobuf:"bytes,4,opt,name=containerisedWorkDefinition,proto3,oneof"`
}

type Work_CompoundWorkDefinition struct {
	CompoundWorkDefinition *CompoundWorkDefinition `protobuf:"bytes,5,opt,name=compoundWorkDefinition,proto3,oneof"`
}

type Work_DynamicWorkGeneratingWorkDefinition struct {
	DynamicWorkGeneratingWorkDefinition *DynamicWorkGeneratingWorkDefinition `protobuf:"bytes,6,opt,name=dynamicWorkGeneratingWorkDefinition,proto3,oneof"`
}

func (*Work_CustomWorkDefinition) isWork_OneofTaskActions() {}

func (*Work_ContainerisedWorkDefinition) isWork_OneofTaskActions() {}

func (*Work_CompoundWorkDefinition) isWork_OneofTaskActions() {}

func (*Work_DynamicWorkGeneratingWorkDefinition) isWork_OneofTaskActions() {}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeCheck     Parameter_TYPE_CHECK   `protobuf:"varint,1,opt,name=typeCheck,proto3,enum=yeetcd.protocol.pipeline.Parameter_TYPE_CHECK" json:"typeCheck,omitempty"`
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  *string                `protobuf:"bytes,3,opt,name=defaultValue,proto3,oneof" json:"defaultValue,omitempty"`
	Choices       []string               `protobuf:"bytes,4,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *Parameter) GetTypeCheck() Parameter_TYPE_CHECK {
	if x != nil {
		return x.TypeCheck
	}
	return Parameter_STRING
}

func (x *Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Parameter) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *Parameter) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

type NotCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *Condition             `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotCondition) Reset() {
	*x = NotCondition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotCondition) ProtoMessage() {}

func (x *NotCondition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotCondition.ProtoReflect.Descriptor instead.
func (*NotCondition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{8}
}

func (x *NotCondition) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type AndCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Condition             `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Condition             `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndCondition) Reset() {
	*x = AndCondition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndCondition) ProtoMessage() {}

func (x *AndCondition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndCondition.ProtoReflect.Descriptor instead.
func (*AndCondition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{9}
}

func (x *AndCondition) GetLeft() *Condition {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *AndCondition) GetRight() *Condition {
	if x != nil {
		return x.Right
	}
	return nil
}

type OrCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Condition             `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Condition             `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrCondition) Reset() {
	*x = OrCondition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrCondition) ProtoMessage() {}

func (x *OrCondition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrCondition.ProtoReflect.Descriptor instead.
func (*OrCondition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{10}
}

func (x *OrCondition) GetLeft() *Condition {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *OrCondition) GetRight() *Condition {
	if x != nil {
		return x.Right
	}
	return nil
}

type WorkContextCondition struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Key           string                       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operand       WorkContextCondition_Operand `protobuf:"varint,2,opt,name=operand,proto3,enum=yeetcd.protocol.pipeline.WorkContextCondition_Operand" json:"operand,omitempty"`
	Value         string                       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkContextCondition) Reset() {
	*x = WorkContextCondition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkContextCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkContextCondition) ProtoMessage() {}

func (x *WorkContextCondition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkContextCondition.ProtoReflect.Descriptor instead.
func (*WorkContextCondition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{11}
}

func (x *WorkContextCondition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WorkContextCondition) GetOperand() WorkContextCondition_Operand {
	if x != nil {
		return x.Operand
	}
	return WorkContextCondition_EQUALS
}

func (x *WorkContextCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PreviousWorkStatusCondition struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        PreviousWorkStatusCondition_Status `protobuf:"varint,1,opt,name=status,proto3,enum=yeetcd.protocol.pipeline.PreviousWorkStatusCondition_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviousWorkStatusCondition) Reset() {
	*x = PreviousWorkStatusCondition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviousWorkStatusCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviousWorkStatusCondition) ProtoMessage() {}

func (x *PreviousWorkStatusCondition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviousWorkStatusCondition.ProtoReflect.Descriptor instead.
func (*PreviousWorkStatusCondition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{12}
}

func (x *PreviousWorkStatusCondition) GetStatus() PreviousWorkStatusCondition_Status {
	if x != nil {
		return x.Status
	}
	return PreviousWorkStatusCondition_SUCCESS
}

type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Conditions:
	//
	//	*Condition_NotCondition
	//	*Condition_AndCondition
	//	*Condition_OrCondition
	//	*Condition_WorkContextCondition
	//	*Condition_PreviousWorkStatusCondition
	Conditions    isCondition_Conditions `protobuf_oneof:"conditions"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{13}
}

func (x *Condition) GetConditions() isCondition_Conditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Condition) GetNotCondition() *NotCondition {
	if x != nil {
		if x, ok := x.Conditions.(*Condition_NotCondition); ok {
			return x.NotCondition
		}
	}
	return nil
}

func (x *Condition) GetAndCondition() *AndCondition {
	if x != nil {
		if x, ok := x.Conditions.(*Condition_AndCondition); ok {
			return x.AndCondition
		}
	}
	return nil
}

func (x *Condition) GetOrCondition() *OrCondition {
	if x != nil {
		if x, ok := x.Conditions.(*Condition_OrCondition); ok {
			return x.OrCondition
		}
	}
	return nil
}

func (x *Condition) GetWorkContextCondition() *WorkContextCondition {
	if x != nil {
		if x, ok := x.Conditions.(*Condition_WorkContextCondition); ok {
			return x.WorkContextCondition
		}
	}
	return nil
}

func (x *Condition) GetPreviousWorkStatusCondition() *PreviousWorkStatusCondition {
	if x != nil {
		if x, ok := x.Conditions.(*Condition_PreviousWorkStatusCondition); ok {
			return x.PreviousWorkStatusCondition
		}
	}
	return nil
}

type isCondition_Conditions interface {
	isCondition_Conditions()
}

type Condition_NotCondition struct {
	NotCondition *NotCondition `protobuf:"bytes,1,opt,name=notCondition,proto3,oneof"`
}

type Condition_AndCondition struct {
	AndCondition *AndCondition `protobuf:"bytes,2,opt,name=andCondition,proto3,oneof"`
}

type Condition_OrCondition struct {
	OrCondition *OrCondition `protobuf:"bytes,3,opt,name=orCondition,proto3,oneof"`
}

type Condition_WorkContextCondition struct {
	WorkContextCondition *WorkContextCondition `protobuf:"bytes,4,opt,name=workContextCondition,proto3,oneof"`
}

type Condition_PreviousWorkStatusCondition struct {
	PreviousWorkStatusCondition *PreviousWorkStatusCondition `protobuf:"bytes,5,opt,name=previousWorkStatusCondition,proto3,oneof"`
}

func (*Condition_NotCondition) isCondition_Conditions() {}

func (*Condition_AndCondition) isCondition_Conditions() {}

func (*Condition_OrCondition) isCondition_Conditions() {}

func (*Condition_WorkContextCondition) isCondition_Conditions() {}

func (*Condition_PreviousWorkStatusCondition) isCondition_Conditions() {}

type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FinalWork     []*Work                `protobuf:"bytes,2,rep,name=finalWork,proto3" json:"finalWork,omitempty"`
	Parameters    map[string]*Parameter  `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkContext   map[string]string      `protobuf:"bytes,4,rep,name=workContext,proto3" json:"workContext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{14}
}

func (x *Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pipeline) GetFinalWork() []*Work {
	if x != nil {
		return x.FinalWork
	}
	return nil
}

func (x *Pipeline) GetParameters() map[string]*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Pipeline) GetWorkContext() map[string]string {
	if x != nil {
		return x.WorkContext
	}
	return nil
}

type Pipelines struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipelines     []*Pipeline            `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipelines) Reset() {
	*x = Pipelines{}
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipelines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipelines) ProtoMessage() {}

func (x *Pipelines) ProtoReflect() protoreflect.Message {
	mi := &file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipelines.ProtoReflect.Descriptor instead.
func (*Pipelines) Descriptor() ([]byte, []int) {
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP(), []int{15}
}

func (x *Pipelines) GetPipelines() []*Pipeline {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

var File_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto protoreflect.FileDescriptor

const file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDesc = "" +
	"\n" +
	"Dcore/protocol/src/main/proto/yeetcd/protocol/pipeline/pipeline.proto\x12\x18yeetcd.protocol.pipeline\"8\n" +
	"\x14CustomWorkDefinition\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\tR\vexecutionId\"G\n" +
	"#DynamicWorkGeneratingWorkDefinition\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\tR\vexecutionId\"E\n" +
	"\x1bContainerisedWorkDefinition\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x10\n" +
	"\x03cmd\x18\x02 \x03(\tR\x03cmd\"V\n" +
	"\x16CompoundWorkDefinition\x12<\n" +
	"\tfinalWork\x18\x03 \x03(\v2\x1e.yeetcd.protocol.pipeline.WorkR\tfinalWork\"8\n" +
	"\x0eWorkOutputPath\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x92\x01\n" +
	"\fPreviousWork\x122\n" +
	"\x04work\x18\x01 \x01(\v2\x1e.yeetcd.protocol.pipeline.WorkR\x04work\x12*\n" +
	"\x10outputPathsMount\x18\x02 \x01(\tR\x10outputPathsMount\x12\"\n" +
	"\fstdOutEnvVar\x18\x03 \x01(\tR\fstdOutEnvVar\"\x9d\a\n" +
	"\x04Work\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12d\n" +
	"\x14customWorkDefinition\x18\x03 \x01(\v2..yeetcd.protocol.pipeline.CustomWorkDefinitionH\x00R\x14customWorkDefinition\x12y\n" +
	"\x1bcontainerisedWorkDefinition\x18\x04 \x01(\v25.yeetcd.protocol.pipeline.ContainerisedWorkDefinitionH\x00R\x1bcontainerisedWorkDefinition\x12j\n" +
	"\x16compoundWorkDefinition\x18\x05 \x01(\v20.yeetcd.protocol.pipeline.CompoundWorkDefinitionH\x00R\x16compoundWorkDefinition\x12\x91\x01\n" +
	"#dynamicWorkGeneratingWorkDefinition\x18\x06 \x01(\v2=.yeetcd.protocol.pipeline.DynamicWorkGeneratingWorkDefinitionH\x00R#dynamicWorkGeneratingWorkDefinition\x12Q\n" +
	"\vworkContext\x18\a \x03(\v2/.yeetcd.protocol.pipeline.Work.WorkContextEntryR\vworkContext\x12J\n" +
	"\voutputPaths\x18\b \x03(\v2(.yeetcd.protocol.pipeline.WorkOutputPathR\voutputPaths\x12J\n" +
	"\fpreviousWork\x18\t \x03(\v2&.yeetcd.protocol.pipeline.PreviousWorkR\fpreviousWork\x12A\n" +
	"\tcondition\x18\n" +
	" \x01(\v2#.yeetcd.protocol.pipeline.ConditionR\tcondition\x1a>\n" +
	"\x10WorkContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14\n" +
	"\x12oneof_task_actions\"\xfc\x01\n" +
	"\tParameter\x12L\n" +
	"\ttypeCheck\x18\x01 \x01(\x0e2..yeetcd.protocol.pipeline.Parameter.TYPE_CHECKR\ttypeCheck\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12'\n" +
	"\fdefaultValue\x18\x03 \x01(\tH\x00R\fdefaultValue\x88\x01\x01\x12\x18\n" +
	"\achoices\x18\x04 \x03(\tR\achoices\"1\n" +
	"\n" +
	"TYPE_CHECK\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x01\x12\v\n" +
	"\aBOOLEAN\x10\x02B\x0f\n" +
	"\r_defaultValue\"Q\n" +
	"\fNotCondition\x12A\n" +
	"\tcondition\x18\x01 \x01(\v2#.yeetcd.protocol.pipeline.ConditionR\tcondition\"\x82\x01\n" +
	"\fAndCondition\x127\n" +
	"\x04left\x18\x01 \x01(\v2#.yeetcd.protocol.pipeline.ConditionR\x04left\x129\n" +
	"\x05right\x18\x02 \x01(\v2#.yeetcd.protocol.pipeline.ConditionR\x05right\"\x81\x01\n" +
	"\vOrCondition\x127\n" +
	"\x04left\x18\x01 \x01(\v2#.yeetcd.protocol.pipeline.ConditionR\x04left\x129\n" +
	"\x05right\x18\x02 \x01(\v2#.yeetcd.protocol.pipeline.ConditionR\x05right\"\xa7\x01\n" +
	"\x14WorkContextCondition\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12P\n" +
	"\aoperand\x18\x02 \x01(\x0e26.yeetcd.protocol.pipeline.WorkContextCondition.OperandR\aoperand\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x15\n" +
	"\aOperand\x12\n" +
	"\n" +
	"\x06EQUALS\x10\x00\"\xa0\x01\n" +
	"\x1bPreviousWorkStatusCondition\x12T\n" +
	"\x06status\x18\x01 \x01(\x0e2<.yeetcd.protocol.pipeline.PreviousWorkStatusCondition.StatusR\x06status\"+\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\x12\a\n" +
	"\x03ANY\x10\x02\"\xe1\x03\n" +
	"\tCondition\x12L\n" +
	"\fnotCondition\x18\x01 \x01(\v2&.yeetcd.protocol.pipeline.NotConditionH\x00R\fnotCondition\x12L\n" +
	"\fandCondition\x18\x02 \x01(\v2&.yeetcd.protocol.pipeline.AndConditionH\x00R\fandCondition\x12I\n" +
	"\vorCondition\x18\x03 \x01(\v2%.yeetcd.protocol.pipeline.OrConditionH\x00R\vorCondition\x12d\n" +
	"\x14workContextCondition\x18\x04 \x01(\v2..yeetcd.protocol.pipeline.WorkContextConditionH\x00R\x14workContextCondition\x12y\n" +
	"\x1bpreviousWorkStatusCondition\x18\x05 \x01(\v25.yeetcd.protocol.pipeline.PreviousWorkStatusConditionH\x00R\x1bpreviousWorkStatusConditionB\f\n" +
	"\n" +
	"conditions\"\xab\x03\n" +
	"\bPipeline\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\tfinalWork\x18\x02 \x03(\v2\x1e.yeetcd.protocol.pipeline.WorkR\tfinalWork\x12R\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v22.yeetcd.protocol.pipeline.Pipeline.ParametersEntryR\n" +
	"parameters\x12U\n" +
	"\vworkContext\x18\x04 \x03(\v23.yeetcd.protocol.pipeline.Pipeline.WorkContextEntryR\vworkContext\x1ab\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.yeetcd.protocol.pipeline.ParameterR\x05value:\x028\x01\x1a>\n" +
	"\x10WorkContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\tPipelines\x12@\n" +
	"\tpipelines\x18\x01 \x03(\v2\".yeetcd.protocol.pipeline.PipelineR\tpipelinesB-Z+github.com/yeetcd/yeetcd/pkg/proto/pipelineb\x06proto3"

var (
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescOnce sync.Once
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescData []byte
)

func file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescGZIP() []byte {
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescOnce.Do(func() {
		file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDesc), len(file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDesc)))
	})
	return file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDescData
}

var file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_goTypes = []any{
	(Parameter_TYPE_CHECK)(0),                   // 0: yeetcd.protocol.pipeline.Parameter.TYPE_CHECK
	(WorkContextCondition_Operand)(0),           // 1: yeetcd.protocol.pipeline.WorkContextCondition.Operand
	(PreviousWorkStatusCondition_Status)(0),     // 2: yeetcd.protocol.pipeline.PreviousWorkStatusCondition.Status
	(*CustomWorkDefinition)(nil),                // 3: yeetcd.protocol.pipeline.CustomWorkDefinition
	(*DynamicWorkGeneratingWorkDefinition)(nil), // 4: yeetcd.protocol.pipeline.DynamicWorkGeneratingWorkDefinition
	(*ContainerisedWorkDefinition)(nil),         // 5: yeetcd.protocol.pipeline.ContainerisedWorkDefinition
	(*CompoundWorkDefinition)(nil),              // 6: yeetcd.protocol.pipeline.CompoundWorkDefinition
	(*WorkOutputPath)(nil),                      // 7: yeetcd.protocol.pipeline.WorkOutputPath
	(*PreviousWork)(nil),                        // 8: yeetcd.protocol.pipeline.PreviousWork
	(*Work)(nil),                                // 9: yeetcd.protocol.pipeline.Work
	(*Parameter)(nil),                           // 10: yeetcd.protocol.pipeline.Parameter
	(*NotCondition)(nil),                        // 11: yeetcd.protocol.pipeline.NotCondition
	(*AndCondition)(nil),                        // 12: yeetcd.protocol.pipeline.AndCondition
	(*OrCondition)(nil),                         // 13: yeetcd.protocol.pipeline.OrCondition
	(*WorkContextCondition)(nil),                // 14: yeetcd.protocol.pipeline.WorkContextCondition
	(*PreviousWorkStatusCondition)(nil),         // 15: yeetcd.protocol.pipeline.PreviousWorkStatusCondition
	(*Condition)(nil),                           // 16: yeetcd.protocol.pipeline.Condition
	(*Pipeline)(nil),                            // 17: yeetcd.protocol.pipeline.Pipeline
	(*Pipelines)(nil),                           // 18: yeetcd.protocol.pipeline.Pipelines
	nil,                                         // 19: yeetcd.protocol.pipeline.Work.WorkContextEntry
	nil,                                         // 20: yeetcd.protocol.pipeline.Pipeline.ParametersEntry
	nil,                                         // 21: yeetcd.protocol.pipeline.Pipeline.WorkContextEntry
}
var file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_depIdxs = []int32{
	9,  // 0: yeetcd.protocol.pipeline.CompoundWorkDefinition.finalWork:type_name -> yeetcd.protocol.pipeline.Work
	9,  // 1: yeetcd.protocol.pipeline.PreviousWork.work:type_name -> yeetcd.protocol.pipeline.Work
	3,  // 2: yeetcd.protocol.pipeline.Work.customWorkDefinition:type_name -> yeetcd.protocol.pipeline.CustomWorkDefinition
	5,  // 3: yeetcd.protocol.pipeline.Work.containerisedWorkDefinition:type_name -> yeetcd.protocol.pipeline.ContainerisedWorkDefinition
	6,  // 4: yeetcd.protocol.pipeline.Work.compoundWorkDefinition:type_name -> yeetcd.protocol.pipeline.CompoundWorkDefinition
	4,  // 5: yeetcd.protocol.pipeline.Work.dynamicWorkGeneratingWorkDefinition:type_name -> yeetcd.protocol.pipeline.DynamicWorkGeneratingWorkDefinition
	19, // 6: yeetcd.protocol.pipeline.Work.workContext:type_name -> yeetcd.protocol.pipeline.Work.WorkContextEntry
	7,  // 7: yeetcd.protocol.pipeline.Work.outputPaths:type_name -> yeetcd.protocol.pipeline.WorkOutputPath
	8,  // 8: yeetcd.protocol.pipeline.Work.previousWork:type_name -> yeetcd.protocol.pipeline.PreviousWork
	16, // 9: yeetcd.protocol.pipeline.Work.condition:type_name -> yeetcd.protocol.pipeline.Condition
	0,  // 10: yeetcd.protocol.pipeline.Parameter.typeCheck:type_name -> yeetcd.protocol.pipeline.Parameter.TYPE_CHECK
	16, // 11: yeetcd.protocol.pipeline.NotCondition.condition:type_name -> yeetcd.protocol.pipeline.Condition
	16, // 12: yeetcd.protocol.pipeline.AndCondition.left:type_name -> yeetcd.protocol.pipeline.Condition
	16, // 13: yeetcd.protocol.pipeline.AndCondition.right:type_name -> yeetcd.protocol.pipeline.Condition
	16, // 14: yeetcd.protocol.pipeline.OrCondition.left:type_name -> yeetcd.protocol.pipeline.Condition
	16, // 15: yeetcd.protocol.pipeline.OrCondition.right:type_name -> yeetcd.protocol.pipeline.Condition
	1,  // 16: yeetcd.protocol.pipeline.WorkContextCondition.operand:type_name -> yeetcd.protocol.pipeline.WorkContextCondition.Operand
	2,  // 17: yeetcd.protocol.pipeline.PreviousWorkStatusCondition.status:type_name -> yeetcd.protocol.pipeline.PreviousWorkStatusCondition.Status
	11, // 18: yeetcd.protocol.pipeline.Condition.notCondition:type_name -> yeetcd.protocol.pipeline.NotCondition
	12, // 19: yeetcd.protocol.pipeline.Condition.andCondition:type_name -> yeetcd.protocol.pipeline.AndCondition
	13, // 20: yeetcd.protocol.pipeline.Condition.orCondition:type_name -> yeetcd.protocol.pipeline.OrCondition
	14, // 21: yeetcd.protocol.pipeline.Condition.workContextCondition:type_name -> yeetcd.protocol.pipeline.WorkContextCondition
	15, // 22: yeetcd.protocol.pipeline.Condition.previousWorkStatusCondition:type_name -> yeetcd.protocol.pipeline.PreviousWorkStatusCondition
	9,  // 23: yeetcd.protocol.pipeline.Pipeline.finalWork:type_name -> yeetcd.protocol.pipeline.Work
	20, // 24: yeetcd.protocol.pipeline.Pipeline.parameters:type_name -> yeetcd.protocol.pipeline.Pipeline.ParametersEntry
	21, // 25: yeetcd.protocol.pipeline.Pipeline.workContext:type_name -> yeetcd.protocol.pipeline.Pipeline.WorkContextEntry
	17, // 26: yeetcd.protocol.pipeline.Pipelines.pipelines:type_name -> yeetcd.protocol.pipeline.Pipeline
	10, // 27: yeetcd.protocol.pipeline.Pipeline.ParametersEntry.value:type_name -> yeetcd.protocol.pipeline.Parameter
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_init() }
func file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_init() {
	if File_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto != nil {
		return
	}
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[6].OneofWrappers = []any{
		(*Work_CustomWorkDefinition)(nil),
		(*Work_ContainerisedWorkDefinition)(nil),
		(*Work_CompoundWorkDefinition)(nil),
		(*Work_DynamicWorkGeneratingWorkDefinition)(nil),
	}
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[7].OneofWrappers = []any{}
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes[13].OneofWrappers = []any{
		(*Condition_NotCondition)(nil),
		(*Condition_AndCondition)(nil),
		(*Condition_OrCondition)(nil),
		(*Condition_WorkContextCondition)(nil),
		(*Condition_PreviousWorkStatusCondition)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDesc), len(file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_goTypes,
		DependencyIndexes: file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_depIdxs,
		EnumInfos:         file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_enumTypes,
		MessageInfos:      file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_msgTypes,
	}.Build()
	File_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto = out.File
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_goTypes = nil
	file_core_protocol_src_main_proto_yeetcd_protocol_pipeline_pipeline_proto_depIdxs = nil
}
