// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: yeetcd/protocol/mock/mock.proto

package mock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MockExecutionService_RunWork_FullMethodName    = "/yeetcd.protocol.mock.MockExecutionService/RunWork"
	MockExecutionService_BuildImage_FullMethodName = "/yeetcd.protocol.mock.MockExecutionService/BuildImage"
)

// MockExecutionServiceClient is the client API for MockExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockExecutionServiceClient interface {
	RunWork(ctx context.Context, in *MockWorkRequest, opts ...grpc.CallOption) (*MockWorkResponse, error)
	BuildImage(ctx context.Context, in *MockImageBuildRequest, opts ...grpc.CallOption) (*MockImageBuildResponse, error)
}

type mockExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockExecutionServiceClient(cc grpc.ClientConnInterface) MockExecutionServiceClient {
	return &mockExecutionServiceClient{cc}
}

func (c *mockExecutionServiceClient) RunWork(ctx context.Context, in *MockWorkRequest, opts ...grpc.CallOption) (*MockWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockWorkResponse)
	err := c.cc.Invoke(ctx, MockExecutionService_RunWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockExecutionServiceClient) BuildImage(ctx context.Context, in *MockImageBuildRequest, opts ...grpc.CallOption) (*MockImageBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockImageBuildResponse)
	err := c.cc.Invoke(ctx, MockExecutionService_BuildImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockExecutionServiceServer is the server API for MockExecutionService service.
// All implementations must embed UnimplementedMockExecutionServiceServer
// for forward compatibility.
type MockExecutionServiceServer interface {
	RunWork(context.Context, *MockWorkRequest) (*MockWorkResponse, error)
	BuildImage(context.Context, *MockImageBuildRequest) (*MockImageBuildResponse, error)
	mustEmbedUnimplementedMockExecutionServiceServer()
}

// UnimplementedMockExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMockExecutionServiceServer struct{}

func (UnimplementedMockExecutionServiceServer) RunWork(context.Context, *MockWorkRequest) (*MockWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWork not implemented")
}
func (UnimplementedMockExecutionServiceServer) BuildImage(context.Context, *MockImageBuildRequest) (*MockImageBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildImage not implemented")
}
func (UnimplementedMockExecutionServiceServer) mustEmbedUnimplementedMockExecutionServiceServer() {}
func (UnimplementedMockExecutionServiceServer) testEmbeddedByValue()                              {}

// UnsafeMockExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockExecutionServiceServer will
// result in compilation errors.
type UnsafeMockExecutionServiceServer interface {
	mustEmbedUnimplementedMockExecutionServiceServer()
}

func RegisterMockExecutionServiceServer(s grpc.ServiceRegistrar, srv MockExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedMockExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MockExecutionService_ServiceDesc, srv)
}

func _MockExecutionService_RunWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockExecutionServiceServer).RunWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockExecutionService_RunWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockExecutionServiceServer).RunWork(ctx, req.(*MockWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockExecutionService_BuildImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockImageBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockExecutionServiceServer).BuildImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockExecutionService_BuildImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockExecutionServiceServer).BuildImage(ctx, req.(*MockImageBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MockExecutionService_ServiceDesc is the grpc.ServiceDesc for MockExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yeetcd.protocol.mock.MockExecutionService",
	HandlerType: (*MockExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunWork",
			Handler:    _MockExecutionService_RunWork_Handler,
		},
		{
			MethodName: "BuildImage",
			Handler:    _MockExecutionService_BuildImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yeetcd/protocol/mock/mock.proto",
}
