// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: yeetcd/protocol/mock/mock.proto

package mock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MockWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Cmd           []string               `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	InputPaths    []string               `protobuf:"bytes,5,rep,name=input_paths,json=inputPaths,proto3" json:"input_paths,omitempty"`
	OutputPaths   []string               `protobuf:"bytes,6,rep,name=output_paths,json=outputPaths,proto3" json:"output_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockWorkRequest) Reset() {
	*x = MockWorkRequest{}
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockWorkRequest) ProtoMessage() {}

func (x *MockWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockWorkRequest.ProtoReflect.Descriptor instead.
func (*MockWorkRequest) Descriptor() ([]byte, []int) {
	return file_yeetcd_protocol_mock_mock_proto_rawDescGZIP(), []int{0}
}

func (x *MockWorkRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MockWorkRequest) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *MockWorkRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *MockWorkRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *MockWorkRequest) GetInputPaths() []string {
	if x != nil {
		return x.InputPaths
	}
	return nil
}

func (x *MockWorkRequest) GetOutputPaths() []string {
	if x != nil {
		return x.OutputPaths
	}
	return nil
}

type MockWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	OutputPaths   map[string]string      `protobuf:"bytes,4,rep,name=output_paths,json=outputPaths,proto3" json:"output_paths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockWorkResponse) Reset() {
	*x = MockWorkResponse{}
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockWorkResponse) ProtoMessage() {}

func (x *MockWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockWorkResponse.ProtoReflect.Descriptor instead.
func (*MockWorkResponse) Descriptor() ([]byte, []int) {
	return file_yeetcd_protocol_mock_mock_proto_rawDescGZIP(), []int{1}
}

func (x *MockWorkResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *MockWorkResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *MockWorkResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *MockWorkResponse) GetOutputPaths() map[string]string {
	if x != nil {
		return x.OutputPaths
	}
	return nil
}

type MockImageBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Artifacts     []string               `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	BuildCmd      string                 `protobuf:"bytes,4,opt,name=build_cmd,json=buildCmd,proto3" json:"build_cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockImageBuildRequest) Reset() {
	*x = MockImageBuildRequest{}
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockImageBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockImageBuildRequest) ProtoMessage() {}

func (x *MockImageBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockImageBuildRequest.ProtoReflect.Descriptor instead.
func (*MockImageBuildRequest) Descriptor() ([]byte, []int) {
	return file_yeetcd_protocol_mock_mock_proto_rawDescGZIP(), []int{2}
}

func (x *MockImageBuildRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MockImageBuildRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MockImageBuildRequest) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *MockImageBuildRequest) GetBuildCmd() string {
	if x != nil {
		return x.BuildCmd
	}
	return ""
}

type MockImageBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ImageRef      string                 `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockImageBuildResponse) Reset() {
	*x = MockImageBuildResponse{}
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockImageBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockImageBuildResponse) ProtoMessage() {}

func (x *MockImageBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yeetcd_protocol_mock_mock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockImageBuildResponse.ProtoReflect.Descriptor instead.
func (*MockImageBuildResponse) Descriptor() ([]byte, []int) {
	return file_yeetcd_protocol_mock_mock_proto_rawDescGZIP(), []int{3}
}

func (x *MockImageBuildResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MockImageBuildResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MockImageBuildResponse) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

var File_yeetcd_protocol_mock_mock_proto protoreflect.FileDescriptor

const file_yeetcd_protocol_mock_mock_proto_rawDesc = "" +
	"\n" +
	"\x1fyeetcd/protocol/mock/mock.proto\x12\x14yeetcd.protocol.mock\"\xa9\x02\n" +
	"\x0fMockWorkRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x10\n" +
	"\x03cmd\x18\x02 \x03(\tR\x03cmd\x12M\n" +
	"\benv_vars\x18\x03 \x03(\v22.yeetcd.protocol.mock.MockWorkRequest.EnvVarsEntryR\aenvVars\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x1f\n" +
	"\vinput_paths\x18\x05 \x03(\tR\n" +
	"inputPaths\x12!\n" +
	"\foutput_paths\x18\x06 \x03(\tR\voutputPaths\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x10MockWorkResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12Z\n" +
	"\foutput_paths\x18\x04 \x03(\v27.yeetcd.protocol.mock.MockWorkResponse.OutputPathsEntryR\voutputPaths\x1a>\n" +
	"\x10OutputPathsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x15MockImageBuildRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x1c\n" +
	"\tartifacts\x18\x03 \x03(\tR\tartifacts\x12\x1b\n" +
	"\tbuild_cmd\x18\x04 \x01(\tR\bbuildCmd\"e\n" +
	"\x16MockImageBuildResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\timage_ref\x18\x03 \x01(\tR\bimageRef2\xd9\x01\n" +
	"\x14MockExecutionService\x12X\n" +
	"\aRunWork\x12%.yeetcd.protocol.mock.MockWorkRequest\x1a&.yeetcd.protocol.mock.MockWorkResponse\x12g\n" +
	"\n" +
	"BuildImage\x12+.yeetcd.protocol.mock.MockImageBuildRequest\x1a,.yeetcd.protocol.mock.MockImageBuildResponseBHZFgithub.com/yeetcd/yeetcd/internal/core/proto/mock/yeetcd/protocol/mockb\x06proto3"

var (
	file_yeetcd_protocol_mock_mock_proto_rawDescOnce sync.Once
	file_yeetcd_protocol_mock_mock_proto_rawDescData []byte
)

func file_yeetcd_protocol_mock_mock_proto_rawDescGZIP() []byte {
	file_yeetcd_protocol_mock_mock_proto_rawDescOnce.Do(func() {
		file_yeetcd_protocol_mock_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yeetcd_protocol_mock_mock_proto_rawDesc), len(file_yeetcd_protocol_mock_mock_proto_rawDesc)))
	})
	return file_yeetcd_protocol_mock_mock_proto_rawDescData
}

var file_yeetcd_protocol_mock_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_yeetcd_protocol_mock_mock_proto_goTypes = []any{
	(*MockWorkRequest)(nil),        // 0: yeetcd.protocol.mock.MockWorkRequest
	(*MockWorkResponse)(nil),       // 1: yeetcd.protocol.mock.MockWorkResponse
	(*MockImageBuildRequest)(nil),  // 2: yeetcd.protocol.mock.MockImageBuildRequest
	(*MockImageBuildResponse)(nil), // 3: yeetcd.protocol.mock.MockImageBuildResponse
	nil,                            // 4: yeetcd.protocol.mock.MockWorkRequest.EnvVarsEntry
	nil,                            // 5: yeetcd.protocol.mock.MockWorkResponse.OutputPathsEntry
}
var file_yeetcd_protocol_mock_mock_proto_depIdxs = []int32{
	4, // 0: yeetcd.protocol.mock.MockWorkRequest.env_vars:type_name -> yeetcd.protocol.mock.MockWorkRequest.EnvVarsEntry
	5, // 1: yeetcd.protocol.mock.MockWorkResponse.output_paths:type_name -> yeetcd.protocol.mock.MockWorkResponse.OutputPathsEntry
	0, // 2: yeetcd.protocol.mock.MockExecutionService.RunWork:input_type -> yeetcd.protocol.mock.MockWorkRequest
	2, // 3: yeetcd.protocol.mock.MockExecutionService.BuildImage:input_type -> yeetcd.protocol.mock.MockImageBuildRequest
	1, // 4: yeetcd.protocol.mock.MockExecutionService.RunWork:output_type -> yeetcd.protocol.mock.MockWorkResponse
	3, // 5: yeetcd.protocol.mock.MockExecutionService.BuildImage:output_type -> yeetcd.protocol.mock.MockImageBuildResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_yeetcd_protocol_mock_mock_proto_init() }
func file_yeetcd_protocol_mock_mock_proto_init() {
	if File_yeetcd_protocol_mock_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yeetcd_protocol_mock_mock_proto_rawDesc), len(file_yeetcd_protocol_mock_mock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yeetcd_protocol_mock_mock_proto_goTypes,
		DependencyIndexes: file_yeetcd_protocol_mock_mock_proto_depIdxs,
		MessageInfos:      file_yeetcd_protocol_mock_mock_proto_msgTypes,
	}.Build()
	File_yeetcd_protocol_mock_mock_proto = out.File
	file_yeetcd_protocol_mock_mock_proto_goTypes = nil
	file_yeetcd_protocol_mock_mock_proto_depIdxs = nil
}
